name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:        
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme XCCleaner clean build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
    - name: Run tests
      run: xcodebuild test -scheme XCCleaner CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
